config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'kaiketools#index'
  get "kaiketools", to: "kaiketools#index"
  resources :search_histories do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :speech_to_text, only: :index do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :search_history

  validates :content, presence: true
end

app/models/kaiketool.rb
class Kaiketool < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :type
  belongs_to :search_history
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :type
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :kaiketools

  def age
    now = Time.zone.now
    age = now.year - user.birthday.year
    age -= 1 if now.month < user.birthday.month || (now.month == user.birthday.month && now.day < user.birthday.day)
    age
  end

end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '' },
    { id: 3, name: '' },
  ]

  include ActiveHash::Associations
  has_many :search_histories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :child_name
    validates :parent_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/ } do
    validates :child_name_kana
    validates :parent_name_kana
  end
  validates :sex_id, presence: true, numericality: { other_than: 1, message: 'を選択して下さい' }
  validates :birthday, presence: true

  has_many :search_histories
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER_KAIKETOOL"] && password == ENV["BASIC_AUTH_PASSWORD_KAIKETOOL"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:child_name, :child_name_kana, :parent_name, :parent_name_kana, :sex_id, :birthday])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to search_history_path(@comment.search_history)
    else
      @search_history = @comment.search_history
      @comments = @search_history.comments
      render "search_histories/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, search_history_id: params[:search_history_id])
  end
end

app/controllers/google_custom_search_controller.rb
class GoogleCustomSearchController < ApplicationController
end

app/controllers/kaiketools_controller.rb
class KaiketoolsController < ApplicationController
  def index
    if user_signed_in?
      @search_history_user = SearchHistory.find_by(user_id: current_user.id)
    else
      @search_history_user = nil
    end
  end
end

app/controllers/search_histories_controller.rb
require 'google/apis/customsearch_v1'
require 'googleauth'
require 'googleauth/stores/file_token_store'

class SearchHistoriesController < ApplicationController
  before_action :set_user

  def index
    @search_histories = SearchHistory.includes(:user).order('created_at DESC').paginate(page: params[:page], per_page: 4)
  end

  def new
    @search_history = SearchHistory.new
  end

  def create
    @search_history = SearchHistory.new(search_history_params)
    if @search_history.save
      redirect_to search_histories_path
    else
      render "search_histories/new"
    end
  end

  def edit
    @search_history = SearchHistory.find(params[:id])
    @search_histories = SearchHistory.where(user_id: current_user.id)
  end

  def update
    if @search_history.update(search_history_params)
      redirect_to edit_search_history_path(@search_history.id)
    else
      render :edit
    end
  end

  def show
    @search_history = SearchHistory.find(params[:id])
    @comment = Comment.new
    @comments = @search_history.comments.includes(:user)
  end

  def destroy
    @search_history = SearchHistory.find(params[:id])
    @search_history.destroy
  end

  def search
    google_custom_search
  end

  private

  def search_history_params
    params.permit(:title, :background, :type_id, :image).merge(user_id: current_user.id)
  end

  def google_custom_search
    if params[:q].blank?
      render "speech_to_text/index"
    end
    @title = params[:q]

    # Custom Search APIを呼び出すためのクライアントを作成します
    client = Google::Apis::CustomsearchV1::CustomSearchAPIService.new
    client.key = ENV['GOOGLE_API_KEY']

    # Custom Search APIの検索パラメータを設定します
    search_params = {
      q: params[:q], # 検索クエリ
      cx: ENV['GOOGLE_CX'], # カスタム検索エンジンID
      num: 4, # 1回のAPIリクエストで返される検索結果の数
      start: 3, # 検索結果の開始位置
      search_type: 'image', # 検索タイプ
      img_size: 'medium', # 画像サイズのフィルター
      cr: 'countryJP', # 検索範囲の指定
      safe: 'active', # セーフサーチの有効化
      gl: 'jp', # 地域の指
      googlehost: 'google.co.jp', # 検索するGoogleドメイン
    }

    # Custom Search APIを呼び出して検索結果を取得します
    search_result = client.list_cses(search_params)

    # 検索結果から画像を抽出して、@images変数に格納します
    if search_result.items.present?
      @image_urls = search_result.items.map { |item| item.link }
    else
    # 検索結果がない場合の処理を記述する
      @image_urls = []
    end
    render "search_histories/new"
  end

  def set_user
    if user_signed_in?
      @search_history_user = SearchHistory.find_by(user_id: current_user.id)
    else
      @search_history_user = nil
    end
  end

end

app/controllers/speech_to_text_controller.rb
class SpeechToTextController < ApplicationController
  before_action :set_user

  def index

  end

  def search
    speech_text
  end
  
  private
  
  def speech_text
    require "google/cloud/speech"
    speech = Google::Cloud::Speech.speech
  
    storage_path = "gs://kaiketool/airpline.flac"
  
    config = { encoding:          :FLAC,    #FLAC、LINEAR16が対応
              sample_rate_hertz: 44_100,   #サンプリングレート
              language_code:     "ja-JP" } #日本語に設定
    audio = { uri: storage_path }
  
    operation = speech.long_running_recognize config: config, audio: audio
  
    puts "Operation started"
  
    operation.wait_until_done!
  
    raise operation.results.message if operation.error?
  
    results = operation.response.results
  
    @transcriptions = ""
    results.each do |result|
      alternatives = result.alternatives
      @transcriptions += "#{alternatives.first.transcript}"
    end
  end

  def set_user
    if user_signed_in?
      @search_history_user = SearchHistory.find_by(user_id: current_user.id)
    else
      @search_history_user = nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/google_custom_search_helper.rb
module GoogleCustomSearchHelper
end

app/helpers/kaiketools_helper.rb
module KaiketoolsHelper
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper
end

app/helpers/speech_to_text_helper.rb
module SpeechToTextHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/google_custom_search/index.html.erb
<h1>Search Images</h1>

<%= form_tag(search_google_custom_search_index_path, method: :get) do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<%= form_with model: @kaiketool, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>
<% if @title.present? %>
  <%= @title %>
<% end  %>
<% if @image_urls.present? %>
  <ul>
    <% @image_urls.each do |url| %>
      <li><%= image_tag url %></li>
    <% end %>
  </ul>
<% end %>

app/views/kaiketools/index.html.erb
<header>
  <div id="splash">
    <div id="splash_logo">
      <%= image_tag "kodomono.png", class:"fadeUp" %>
      <%= image_tag "kaiketu2.png", class:"fadeUp" %>
    </div>
  </div>
<header>

<body>
  <div class="kaiketu">
    <div class="kaiketu-btn">
        <%= button_to "かいけつする？", speech_to_text_index_path, method: :get, class: "btn-link" %>
    </div>
    <ul class="slider">
      <li class="slider-item slider-item01"><img src="<%= asset_path('utyu.jpg') %>" width="100%" height="100%"></li>
      <li class="slider-item slider-item02"><img src="<%= asset_path('utyu3.jpg') %>" width="100%" height="100%"></li>
      <li class="slider-item slider-item03"><img src="<%= asset_path('utyu2.jpg') %>" width="100%" height="100%"></li>
    </ul>
  </div>
  <main>
    <section>
    <!--/area1-->
      <div class="contents">
        <div class="content">
          <div class="content-up">
            <h2>なせなせ期とは・・・</h2>
            <br/>
          </div>
          <div class="content-down">
            <h4>
              子供たちは、成長の過程で「なぜなぜ期」と呼ばれる時期があります。<br/>
              この時期になると、子供たちは世界の中で起こることに対して疑問を持ち<br/>
              何度も「なぜ？」と質問を繰り返します。
            </h4>
          </div>
        </div>
        <div>
          <%= image_tag "1.png" , size: '400x288' %>
        </div>
      </div>
    </section>
    <section>
    <!--/area2-->
      <div class="contents">
        <div>
          <%= image_tag "2.png", size: '287x300' %>
        </div>
        <div class="content">
          <div class="content-up">
            <h2>こどものなぜなぜを解決しましょう</h2>
            <br/>
          </div>
          <div class="content-down">
            <h4>
              この「かいけつ〜る」を使って<br/>
              子供たちの好奇心を刺激し、新しい知識を獲得しよう。<br/>
              この時期に積極的に質問に答えること子供たちは<br/>
              コミュニケーション能力や思考力を発展させ自信をつけることができます。
            </h4>
          </div>
        </div>
      </div>
    </section>
    <section>
    <!--/area3-->
      <div>
        <div class="contents">
          <div class="content">
            <div class="content-up">
              <h2>解決したなぜなぜをみんなでシェアしよう</h2>
              <br/>
            </div>
            <div class="content-down">
              <h4>
              みんなの投稿を見ることで子供と一緒に新しい発見や<br/>
              同じなぜなぜを共感できます。<br/>
              ぜひシェアしてあなたの友人やフォロワーさんと意見交換しましょう！
              </h4>
            </div>
          </div>
          <div>
          <%= image_tag "5.png", size: '332x350' %>
          </div>
        </div>
      </div>
    </section>
    <section>
    <!--/area4-->
      <%= image_tag "utyujin.png", class:"fuwafuwa" %>
      <div class="contents">
        <div class="link">
          <%= link_to "みんなの投稿", search_histories_path , class:"btn-link" %>
        </div>
      </div>
    </section>
  </main>

  <footer id="footer">
    <small>&copy; kaiketool</small>
    <p id="page-top"><%= link_to "かいけつしよう！", speech_to_text_index_path%></p>
  </footer>

</body>
  <%= javascript_pack_tag 'first' %>
  <%= javascript_pack_tag 'link' %>

app/views/search_histories/edit.html.erb
<div class="edit-main">
  プロフィール
  <div class="edit-wrap">
    <div class="edit-html">
      <input id="tab-1" type="radio" name="tab" class="now" checked><label for="tab-1" class="tabb">いま</label>
      <input id="tab-2" type="radio" name="tab" class="edit"><label for="tab-2" class="tabb">へんしゅう</label>
      <div class="login-form-edit">
        <div class="edit-now-htm">
          <div class="group">
            <label class="label" >お子さんのなまえ</label>
            <p class="input" id="child-name">
            <%= @search_history.user.child_name %>
            </p>
          </div>
          <div class="group">
            <label class="label" >子供のふりがな</label>
            <p class="input" id="child-reading">
            <%= @search_history.user.child_name_kana %></p>
          </div>
          <div class="group">
            <label class="label" >誕生日</label>
            <p class="input" id="child-birthday">
            <%= @search_history.user.birthday %></p>
          </div>
          <div class="group">
            <label class="label" >性別</label>
            <p class="input" id="child-gender">
            <%= @search_history.user.sex_id %></p>
          </div>
          <div class="group">
            <label class="label" >お母さん、お父さんの名前</label>
            <p class="input" id="parent-name">
            <%= @search_history.user.parent_name %></p>
          </div>
          <div class="group">
            <label class="label" >お母さん、お父さんのふりがな</label>
            <p class="input" id="parent-reading">
            <%= @search_history.user.parent_name_kana %></p>
          </div>
        </div>
        <div class="edit-edit-htm">
        <%= form_with model: @user, url: user_registration_path, local: true do |f| %>
          <div class="group">
            <%= f.label :お子さんのなまえ, class:"label" %><br />
            <%= f.text_field :child_name, value: @search_history.user.child_name, autofocus: true, autocomplete: "", class:"input" %>
          </div>
          <div class="group">
            <%= f.label :子供のふりがな,class:"label"  %><br />
            <%= f.text_field :child_name_kana, value: @search_history.user.child_name_kana, autofocus: true, autocomplete: "", class:"input" %>
          </div>
          <div class="group">
            <%= f.label :性別, class:"label" %><br />
            <div class="sel-inp">
              <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"sel-inp"}) %>
            </div>
          </div> 
          <div class="group">
            <%= f.label :お父さん・お母さんのなまえ, class:"label" %><br />
            <%= f.text_field :parent_name, value: @search_history.user.parent_name, autofocus: true, autocomplete: "", class:"input" %>
          </div>
          <div class="group">
            <%= f.label :フリガナ（半角カナ）, class:"label" %><br />
            <%= f.text_field :parent_name_kana, value: @search_history.user.parent_name_kana, autofocus: true, autocomplete: "", class:"input" %>
          </div>
          <div class="group">
            <%= f.submit "へんしゅう" , class:"button"%>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="test">
  検索履歴
  </div>
  <div class="history-htm1-prof" id="content">
    <div class="profile-history">
      <div class="child-info">
        <div class="group">
          <label for="child-name"></label>
          <% @search_histories.each do |history| %>
            <p class="input_history" id="child-name">
            <%= history.title %>
            <%= image_tag (history.image), size: '400x350' %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to(root_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>もどる</span>
    <%= image_tag 'ufo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/search_histories/index.html.erb
<div class="history-main">
  <div class="history-wrap">
    <div class="history-html">
      <div class="history-title">
      みんなのなぜなぜ
      </div>
      <%= image_tag '333.png' , size: '90x90' ,class: "rocket-icon" %>
      <%= will_paginate @search_histories, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
      <div class="history-form">
        <% @search_histories.each do |history| %>
        <div class="history-htm1" id="content">
          <div class="his-con">
            <div class="his-top">
              <div class="his-son">
                <%= history.user.child_name %>
              </div>
              <% if history.user.sex_id == 2 %>
                くん<p>&emsp;</p>
              <% else %>
                ちゃん<p>&emsp;</p>
              <% end %>
              <div class="his-birthday">
                <%= history.age %>
              </div>
                さい&emsp;のなぜなぜ
            </div>

            <div class="his-down">
              <div class="his-left">
                <%= image_tag (history.image), size: '400x350' %>
              </div>
              <div class="his-rigth">
                <div class="title-con">
                  <div class="his-title-ex">
                    けんさくキーワード
                  </div>
                  <div class="his-tit">
                    <%= history.title %>
                  </div>
                </div>
                <div class="exp-con">
                  <div class="his-exp-ex">
                  キーワードのせつめい
                  </div>
                  <div class="his-exp">
                  キーワードの説明が入ります。
                  </div>
                </div>
                <div class="his-right-down">
                  <div class="his-back-ex">
                    なぜ？となったきっかけ
                      <%# <%= history.type.name %>
                  </div>
                  <div class="his-back">
                    
                    <%# <%= history.background %><br> 
                  </div>
                  <div class="under-image">
                    <%= link_to search_history_path(history.id) do %>
                      <%= image_tag "coment.png", size: '35x35',class:"under-btn"%>&emsp;&emsp;
                    <% end %>
                      <%= image_tag "rituit.png", size: '35x35', class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "heart.png", size: '35x35',class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "up.png", size: '35x35',class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "kyouyu.png", size: '35x35',class:"under-btn" %>&emsp;
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <%= will_paginate @search_histories, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
    </div>
  </div>
</div>
<%= link_to(speech_to_text_index_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>もどる</span>
    <%= image_tag 'ufo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/search_histories/new.html.erb
<div class="result-main">
  <div class="result-wrap">
    <div class="result-html">
      <div class="result-title">
      いちばん近い画像をほぞんしよう<br>
      <% unless user_signed_in? %>
        <%= link_to "とうろくすればほぞんできるよ", new_user_registration_path , class:"btn-link" %>
      <% end %>
      <%= image_tag "555.png", class:"by--u" %>
      </div>
      <div class="result-form">
        <% @image_urls.each do |url|  %>
        <div class="result-htm1">
          <%= form_with model: @search_history, url: search_histories_path, method: :post, local: true do |f|%>
          <div class="htm1-con">
            <div class="htm1-up">
              <div class="right-title">
                <div class="htm1-right">
                  <%= f.label :title, "なぜなぜキーワード" %><br>
                  <%= f.hidden_field :title, value: @title %>
                  <!-- valueオプションを使って、@titleをフォームに表示する -->
                </div>
                <div class="htm1-title">
                  <%= @title %>
                </div>
              </div>
              <div class="htm1-left">
                <% if user_signed_in? %>
                  <%= f.submit "これだ！", class:"submit-link"  %>
                <% end %>
              </div>
            </div>

            <div class="htm1-down">
              <div class="img-tit">
                <%= f.label :image, "なぜなぜ画像" %><br>
                <%= f.hidden_field :image, value: url %>
                <!-- hidden_fieldを使って、@image_urlsの情報をformに送信する -->
              </div>
              <div class="result-img">
                <%= image_tag url, size: '350x200' %>
              </div>
              <div class="exp-tit">
                <%= f.label :background, "なぜなぜの説明" %><br>
              </div>
              <div class="result-exp">

                <%# <%= f.text_area :background,  class:"result-exp" %> 
              </div>
            </div>
          </div>

        <div class="huga">
          <%= f.label :type_id, "なぜなぜの種類" %><br>
          <div class="hoge">
            <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"hoge"}) %>
          </div>
        </div>

          <% end  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to(speech_to_text_index_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>もどる</span>
    <%= image_tag 'ufo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/search_histories/show.html.erb
<div class="history-main">
  <div class="history-wrap">
    <div class="history-html">
      <div class="history-title">

      </div>
      <%= image_tag '333.png' , size: '90x90' ,class: "rocket-icon" %>
      <div class="history-form">
        <div class="history-htm1" id="content">
          <div class="his-con">
            <div class="his-top">
              <div class="his-son">
                <%= @search_history.user.child_name %>
              </div>
              <% if @search_history.user.sex_id == 2 %>
                くん<p>&emsp;</p>
              <% else %>
                ちゃん<p>&emsp;</p>
              <% end %>
              <div class="his-birthday">
                <%= @search_history.age %>
              </div>
                さい&emsp;のなぜなぜ
            </div>

            <div class="his-down">
              <div class="his-left">
                <%= image_tag (@search_history.image), size: '400x350' %>
              </div>
              <div class="his-rigth">
                <div class="title-con">
                  <div class="his-title-ex">
                    けんさくキーワード
                  </div>
                  <div class="his-tit">
                    <%= @search_history.title %>
                  </div>
                </div>
                <div class="exp-con">
                  <div class="his-exp-ex">
                  キーワードのせつめい
                  </div>
                  <div class="his-exp">
                  キーワードの説明が入ります。
                  </div>
                </div>
                <div class="his-right-down">
                  <div class="his-back-ex">
                    なぜ？となったきっかけ
                      <%# <%= history.type.name %>
                  </div>
                  <div class="his-back">
                    <%# <%= @search_history.background %>
                  </div>
                  <div class="under-image">
                    <%= link_to search_history_path(@search_history.id) do %>
                      <%= image_tag "coment.png", size: '35x35',class:"under-btn"%>&emsp;&emsp;
                    <% end %>
                      <%= image_tag "rituit.png", size: '35x35', class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "heart.png", size: '35x35',class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "up.png", size: '35x35',class:"under-btn" %>&emsp;&emsp;
                      <%= image_tag "kyouyu.png", size: '35x35',class:"under-btn" %>&emsp;
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="history-comment">
        <div class="__comments">
          <% if user_signed_in? %>
            <%= form_with model: [@search_history, @comment],local: true do |f| %>
              <div class="field">
                <%= f.label :content, "コメント" %><br />
                <%= f.text_field :content, id:"comment_content" %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %>
          <% end %>
          <ul class="comments_lists">
              <li class="comments_list">
              <% @comments.each do |comment| %>
                <%= comment.content %>
                <%= comment.user.parent_name +
                                        "("  +
                    comment.user.child_name  +
                                      "の親)" %><br/>
                <%# <%= link_to comment.user.parent_name, user_path(comment.user.id), class: :comment_user %>
              <% end %>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to(search_histories_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>もどる</span>
    <%= image_tag 'ufo.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

app/views/speech_to_text/index.html.erb
<div class="search-main">
  <%= image_tag "kaseijin.png", class:"kaseijin" %>
  <div class="search-wrap">
    <div class="search-html">
      <div class="search-title">
      わからないことを調べよう
      </div>
      <div class="search-icn-voice">
      きいてみる？
      </div>
      <div class="search-icn">
      <%= link_to(search_speech_to_text_index_path, class:"") do %>
        <%= image_tag '25.png' , size: '155x120', class:"" %>
      <% end %>
      </div>
      <div class="search-form">
      <%= form_with url: search_search_histories_path, method: :get, local: true do |f| %>
        <%= f.text_field :q, class:"input" %>
      </div>
      <div class="search-btn">
        <%= f.submit "けんさく", class:"button" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/speech_to_text/search.html.erb
<div class="search-main">
  <div class="search-wrap">
    <div class="search-html">
      <div class="search-title">
      わからないことを調べよう
      </div>
      <div class="search-form">
        <div class="search-voice-htm">
              <div class="">はなしかけてみよ
              </div>
              <div class="">
              <%= link_to(search_speech_to_text_index_path, class:"") do %>
                <%= image_tag 'voice.png' , size: '60x120', class:"" %>
              <% end %>
              </div>
          <div class="hr"></div>
          <div class="foot-lnk">
            <a href=""></a>
          </div>
        </div>
        <div class="search-htm">
              <div class="">
              <%= form_with url: search_search_histories_path, method: :get, local: true do |f| %>
                <%= f.text_field :q, value: @transcriptions, class:"input" %><br/>
                <%= f.submit "けんさく", class:"button" %>
              <% end %>
              </div>
          <div class="hr"></div>
          <div class="foot-lnk">
            <a href=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>